<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MerchantProcessing.Consolidator.Worker-d876b8ea-4c99-4a99-8b31-ea3e4f89a26d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.9" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MerchantProcessing.Domain\MerchantProcessing.Domain.csproj" />
    <ProjectReference Include="..\MerchantProcessing.Infrastructure\MerchantProcessing.Infrastructure.csproj" />
  </ItemGroup>
</Project>
